import { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { getServerSession } from "next-auth/next";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import Navbar from "@/components/Navbar";
import ClientSessionProvider from "@/providers/ClientSessionProvider"; // Client Component for SessionProvider
import Container from "@/components/Container/Container";
import { Toaster } from "react-hot-toast";
import { options } from "@/lib/hotToast";
import UserContextProvider from "@/context/UserContextProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Bills",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions); // Fetch session server-side

  return (
    <html lang="en">
      <UserContextProvider>
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <ClientSessionProvider session={session}> {/* Pass session to Client Component */}
            <Container>
              <Navbar 
              // searchParams={searchParams}
              />
              {children}
              <Toaster 
                position="top-center" 
                toastOptions={options} 
                gutter={24} />
              </Container>
          </ClientSessionProvider>
        </body>
      </UserContextProvider>
    </html>
  );
}
